# Generated by Django 4.0.3 on 2022-04-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=40)),
                ('marca_alimento', models.CharField(max_length=40)),
                ('precio_dolares', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Integrante_Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('profesion', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=50)),
                ('mascota', models.BooleanField(default=False)),
                ('nombre_mascota', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=40)),
                ('edad_mascota', models.IntegerField()),
                ('raza_mascota', models.CharField(max_length=40)),
            ],
        ),
    ]
