# Generated by Django 4.0.3 on 2022-04-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Family_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrante_familia',
            name='mascota',
        ),
    ]
